# Không sử dụng trường "version" vì nó đã lỗi thời trong Docker Compose mới

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - microservice-net
    depends_on:
      - customer-services
      - order-services
      - product-services

  customer-services:
    build:
      context: ./customer-services
    ports:
      - "8083:8083"
    networks:
      - microservice-net

  order-services:
    build:
      context: ./order-services
    ports:
      - "8081:8081"
    networks:
      - microservice-net

  product-services:
    build:
      context: ./product-services
    ports:
      - "8082:8082"
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge