server:
  port: 8080

spring:
  application:
    name: apiGateWay
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**, /api/products/**
          filters:
            - StripPrefix=1
            
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/customer/**, /api/customers/**
          filters:
            - StripPrefix=1
            
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/order/**, /api/orders/**server:
  port: 8080

spring:
  application:
    name: apiGateWay
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/product/**, /api/products/**
            
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/customer/**, /api/customers/**
            
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/order/**, /api/orders/**
          filters:
            - StripPrefix=1