server:
  port: 8083
  
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb
      database: customerdb
      auto-index-creation: true